[package]
name = "medici_core"
version = "0.1.0"
authors = ["Bert Proesmans <bproesmans@hotmail.com>"]

[dependencies]
value_from_type_macros = "1.0.3"
value_from_type_traits = "1.0.2"

failure = "0.1.1"
maplit = "1.0.1"
[dev-dependencies]
clippy = { version = "*" }
