[package]
name = "value_from_type_traits"
version = "1.0.0"
authors = ["Bert Proesmans <bproesmans@hotmail.com>"]
description = "Traits accompanying the value_from_type_macros crate"
license = "MIT"

[dependencies]
