[package]
name = "medici_derive"
version = "0.1.0"
authors = ["Bert Proesmans <bproesmans@hotmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.13.0", features = ['full'] }
quote = "0.5.0"
proc-macro2 = { version = "0.3.0", features = ["nightly"] }
